spring:
  application:
    name: search-service

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}

server:
  port: 8082

cors:
  allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG

geo:
  service:
    url: ${GEO_SERVICE_URL:http://localhost:8085}
