
import { SearchResult } from '@/types/search';

export const MOCK_RESULTS: SearchResult[] = [
    // --- HIGH-TECH ---
    {
        id: '1',
        name: 'iPhone 15 Pro Max',
        description: 'Titanium Black, 256GB. Le dernier cri de la technologie Apple avec puce A17 Pro.',
        price: 950000,
        type: 'product',
        category: 'High-Tech',
        city: 'Yaoundé',
        rating: 4.9,
        images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500'],
        shop: { name: 'iStore Bastos', address: 'Bastos, Yaoundé' },
        location: { lat: 3.8752, lng: 11.5123 },
        tags: ['Apple', 'Smartphone', 'Luxe'],
        detailsUrl: '/search/1'
    },
    {
        id: '2',
        name: 'HP EliteBook 840 G8',
        description: 'Laptop professionnel, Core i7 11th Gen, 16GB RAM, 512GB SSD. Parfait pour le travail.',
        price: 450000,
        type: 'product',
        category: 'High-Tech',
        city: 'Yaoundé',
        rating: 4.6,
        images: ['https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500'],
        shop: { name: 'Fanta HighTech', address: 'Avenue Kennedy, Yaoundé' },
        location: { lat: 3.8640, lng: 11.5200 },
        tags: ['Ordinateur', 'HP', 'Travail'],
        detailsUrl: '/search/2'
    },
    {
        id: '3',
        name: 'PlayStation 5 Slim',
        description: 'Console de jeux Sony PS5 édition standard avec lecteur disque.',
        price: 400000,
        type: 'product',
        category: 'High-Tech',
        city: 'Yaoundé',
        rating: 4.8,
        images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500'],
        shop: { name: 'GameWorld Mvog-Mbi', address: 'Mvog-Mbi, Yaoundé' },
        location: { lat: 3.8545, lng: 11.5280 },
        tags: ['Gaming', 'Console', 'Sony'],
        detailsUrl: '/search/3'
    },
    {
        id: '4',
        name: 'Samsung Galaxy Tab S9',
        description: 'Tablette Android haute performance, écran AMOLED, S-Pen inclus.',
        price: 600000,
        type: 'product',
        category: 'High-Tech',
        city: 'Yaoundé',
        rating: 4.7,
        images: ['https://images.unsplash.com/photo-1542751110-97427bbecf20?w=500'],
        shop: { name: 'Samsung Experience', address: 'Bastos, Yaoundé' },
        location: { lat: 3.8745, lng: 11.5115 },
        tags: ['Tablette', 'Android', 'Samsung'],
        detailsUrl: '/search/4'
    },

    // --- RESTAURATION ---
    {
        id: '5',
        name: 'Poulet DG Royal',
        description: 'Plat traditionnel camerounais revisité : poulet fermier, plantains mûrs, légumes frais.',
        price: 8500,
        type: 'product',
        category: 'Restauration',
        city: 'Yaoundé',
        rating: 4.9,
        images: ['https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500'],
        shop: { name: 'Le Bois Sainte Anastasie', address: 'Warda, Yaoundé' },
        location: { lat: 3.8680, lng: 11.5140 },
        tags: ['Cuisine locale', 'Gastronomie', 'Diner'],
        detailsUrl: '/search/5'
    },
    {
        id: '6',
        name: 'Pizza Sorento XL',
        description: 'Pizza géante pepperoni, champignons, fromage double. Au feu de bois.',
        price: 6000,
        type: 'product',
        category: 'Restauration',
        city: 'Yaoundé',
        rating: 4.5,
        images: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500'],
        shop: { name: 'Sorento Pizzeria', address: 'Omnisport, Yaoundé' },
        location: { lat: 3.8810, lng: 11.5310 },
        tags: ['Italien', 'Pizza', 'Livraison'],
        detailsUrl: '/search/6'
    },
    {
        id: '7',
        name: 'Ndole Crevettes',
        description: 'Spécialité Douala avec miondos. Cuit avec amour et épices locales.',
        price: 4500,
        type: 'product',
        category: 'Restauration',
        city: 'Yaoundé',
        rating: 4.8,
        images: ['https://images.unsplash.com/photo-1574484284008-59d7aa986528?w=500'],
        shop: { name: 'Marmite du Pays', address: 'Mvan, Yaoundé' },
        location: { lat: 3.8355, lng: 11.5165 },
        tags: ['Cameroun', 'Traditionnel', 'Ndole'],
        detailsUrl: '/search/7'
    },
    {
        id: '8',
        name: 'Burger King Menu Steakhouse',
        description: 'Burger premium avec bacon, sauce BBQ, frites et boisson.',
        price: 5800,
        type: 'product',
        category: 'Restauration',
        city: 'Yaoundé',
        rating: 4.4,
        images: ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500'],
        shop: { name: 'Burger King', address: 'Carrefour Warda, Yaoundé' },
        location: { lat: 3.8660, lng: 11.5105 },
        tags: ['Fast Food', 'Burger', 'US'],
        detailsUrl: '/search/8'
    },

    // --- MODE ---
    {
        id: '9',
        name: 'Nike Air Force 1',
        description: 'La classique blanche. Indémodable, confortable et stylée.',
        price: 40000,
        type: 'product',
        category: 'Mode',
        city: 'Yaoundé',
        rating: 4.7,
        images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500'],
        shop: { name: 'City Sport', address: 'Mvan, Yaoundé' },
        location: { lat: 3.8360, lng: 11.5190 },
        tags: ['Sneakers', 'Nike', 'Mode'],
        detailsUrl: '/search/9'
    },
    {
        id: '10',
        name: 'Costume 3 Pièces Bleu Nuit',
        description: 'Coupe italienne cintrée, tissu laine super 120s. Élégance assurée.',
        price: 120000,
        type: 'product',
        category: 'Mode',
        city: 'Yaoundé',
        rating: 4.8,
        images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500'],
        shop: { name: 'Men Fashion Week', address: 'Bastos, Yaoundé' },
        location: { lat: 3.8765, lng: 11.5135 },
        tags: ['Homme', 'Luxe', 'Costume'],
        detailsUrl: '/search/10'
    },
    {
        id: '11',
        name: 'Robe de Soirée Rouge',
        description: 'Robe longue en satin, dos nu. Idéale pour galas et mariages.',
        price: 65000,
        type: 'product',
        category: 'Mode',
        city: 'Yaoundé',
        rating: 4.9,
        images: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500'],
        shop: { name: 'Glamour House', address: 'Montée Anne Rouge, Yaoundé' },
        location: { lat: 3.8710, lng: 11.5205 },
        tags: ['Femme', 'Soirée', 'Robe'],
        detailsUrl: '/search/11'
    },

    // --- AUTOMOBILE ---
    {
        id: '12',
        name: 'Vidange Complète + Filtres',
        description: 'Forfait vidange huile synthétique 5W30, remplacement filtre à huile et air.',
        price: 25000,
        type: 'service',
        category: 'Automobile',
        city: 'Yaoundé',
        rating: 4.6,
        images: ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=500'],
        shop: { name: 'Garage Auto Expert', address: 'Mvog-Mbi, Yaoundé' },
        location: { lat: 3.8550, lng: 11.5240 },
        tags: ['Mécanique', 'Entretien', 'Auto'],
        detailsUrl: '/search/12'
    },
    {
        id: '13',
        name: 'Lavage Auto Premium',
        description: 'Nettoyage intérieur/extérieur, cire lustrante, aspiration complète.',
        price: 5000,
        type: 'service',
        category: 'Automobile',
        city: 'Yaoundé',
        rating: 4.5,
        images: ['https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=500'],
        shop: { name: 'Total Wash', address: 'Melen, Yaoundé' },
        location: { lat: 3.8730, lng: 11.4990 },
        tags: ['Lavage', 'Propreté', 'Auto'],
        detailsUrl: '/search/13'
    },
    {
        id: '14',
        name: 'Pneus Michelin 205/55 R16',
        description: 'Pneus été haute performance, adhérence optimale sur sol mouillé.',
        price: 65000,
        type: 'product',
        category: 'Automobile',
        city: 'Yaoundé',
        rating: 4.8,
        images: ['https://images.unsplash.com/photo-1578844251758-2f71da64522f?w=500'],
        shop: { name: 'CamerTyres', address: 'Tsinga, Yaoundé' },
        location: { lat: 3.8850, lng: 11.5050 },
        tags: ['Pneus', 'Michelin', 'Sécurité'],
        detailsUrl: '/search/14'
    },

    // --- BEAUTÉ & SANTÉ ---
    {
        id: '15',
        name: 'Massage Relaxant 1h',
        description: 'Massage aux huiles essentielles, détente musculaire profonde.',
        price: 15000,
        type: 'service',
        category: 'Beauté',
        city: 'Yaoundé',
        rating: 4.9,
        images: ['https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=500'],
        shop: { name: 'Spa du Mont Fébé', address: 'Mont Fébé, Yaoundé' },
        location: { lat: 3.9000, lng: 11.5000 },
        tags: ['Spa', 'Détente', 'Massage'],
        detailsUrl: '/search/15'
    },
    {
        id: '16',
        name: 'Coupe Homme Dégradé',
        description: 'Coupe tendance avec finitions rasoir et soin barbe.',
        price: 3000,
        type: 'service',
        category: 'Beauté',
        city: 'Yaoundé',
        rating: 4.7,
        images: ['https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=500'],
        shop: { name: 'Barber King', address: 'Biyem-Assi, Yaoundé' },
        location: { lat: 3.8400, lng: 11.4900 },
        tags: ['Coiffure', 'Barbe', 'Homme'],
        detailsUrl: '/search/16'
    },
    {
        id: '17',
        name: 'Doliprane 1000mg',
        description: 'Paracétamol pour douleurs et fièvre. Boite de 8 comprimés.',
        price: 500,
        type: 'product',
        category: 'Santé',
        city: 'Yaoundé',
        rating: 5.0,
        images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500'],
        shop: { name: 'Pharmacie du Soleil', address: 'Marché Central, Yaoundé' },
        location: { lat: 3.8620, lng: 11.5210 },
        tags: ['Pharmacie', 'Médicament', 'Santé'],
        detailsUrl: '/search/17'
    },

    // --- COMMERCES & SERVICES ---
    {
        id: '18',
        name: 'Supermarché Casino',
        description: 'Votre supermarché pour les courses du quotidien. Rayon frais, boucherie, boulangerie.',
        price: 0,
        type: 'shop',
        category: 'Supermarché',
        city: 'Yaoundé',
        rating: 4.3,
        images: ['https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=500'],
        shop: { name: 'Casino', address: 'Mvog-Mbi, Yaoundé' },
        location: { lat: 3.8570, lng: 11.5260 },
        tags: ['Courses', 'Alimentation', 'Casino'],
        detailsUrl: '/search/18'
    },
    {
        id: '19',
        name: 'Dovv Essos',
        description: 'Supermarché local, produits frais et prix abordables.',
        price: 0,
        type: 'shop',
        category: 'Supermarché',
        city: 'Yaoundé',
        rating: 4.2,
        images: ['https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=500'],
        shop: { name: 'Dovv', address: 'Essos, Yaoundé' },
        location: { lat: 3.8800, lng: 11.5400 },
        tags: ['Supermarché', 'Dovv', 'Local'],
        detailsUrl: '/search/19'
    },
    {
        id: '20',
        name: 'Boulangerie Acropole',
        description: 'Pains chauds, viennoiseries, pâtisseries fines et sandwichs.',
        price: 0,
        type: 'shop',
        category: 'Boulangerie',
        city: 'Yaoundé',
        rating: 4.8,
        images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500'],
        shop: { name: 'Acropole', address: 'Centre Ville, Yaoundé' },
        location: { lat: 3.8610, lng: 11.5160 },
        tags: ['Pain', 'Croissant', 'Gâteaux'],
        detailsUrl: '/search/20'
    },
    {
        id: '21',
        name: 'Pressing 5 étoiles',
        description: 'Nettoyage à sec, repassage, blanchisserie. Service rapide.',
        price: 1500,
        type: 'service',
        category: 'Services',
        city: 'Yaoundé',
        rating: 4.4,
        images: ['https://images.unsplash.com/photo-1517677208171-0bc6799a4c6d?w=500'],
        shop: { name: 'Pressing 5 étoiles', address: 'Ngodas, Yaoundé' },
        location: { lat: 3.8500, lng: 11.5100 },
        tags: ['Linge', 'Propre', 'Vêtements'],
        detailsUrl: '/search/21'
    },

    // --- HOTELLERIE & LOISIRS ---
    {
        id: '22',
        name: 'Hilton Hotel Yaoundé',
        description: 'Hôtel 5 étoiles au cœur de la ville. Piscine, restaurant panoramique.',
        price: 150000,
        type: 'service',
        category: 'Hôtellerie',
        city: 'Yaoundé',
        rating: 4.6,
        images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500'],
        shop: { name: 'Hilton', address: 'Boulevard du 20 Mai, Yaoundé' },
        location: { lat: 3.8655, lng: 11.5155 },
        tags: ['Luxe', 'Hôtel', 'Chambre'],
        detailsUrl: '/search/22'
    },
    {
        id: '23',
        name: 'Canal Olympia',
        description: 'Cinéma moderne, dernières sorties films, salle climatisée.',
        price: 1500,
        type: 'service',
        category: 'Loisirs',
        city: 'Yaoundé',
        rating: 4.5,
        images: ['https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500'],
        shop: { name: 'Canal Olympia', address: 'Université Yaoundé 1, Yaoundé' },
        location: { lat: 3.8900, lng: 11.5030 },
        tags: ['Cinéma', 'Film', 'Sortie'],
        detailsUrl: '/search/23'
    },
    {
        id: '24',
        name: 'Mont Fébé Hotel',
        description: 'Hôtel historique avec vue imprenable sur la ville. Golf et tennis.',
        price: 120000,
        type: 'service',
        category: 'Hôtellerie',
        city: 'Yaoundé',
        rating: 4.4,
        images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=500'],
        shop: { name: 'Mont Fébé', address: 'Mont Fébé, Yaoundé' },
        location: { lat: 3.9010, lng: 11.5010 },
        tags: ['Hôtel', 'Vue', 'Golf'],
        detailsUrl: '/search/24'
    },

    // --- DIVERS ---
    {
        id: '25',
        name: 'Librairie des Peuples Noirs',
        description: 'Large choix de livres africains, romans, scolaires et papeterie.',
        price: 0,
        type: 'shop',
        category: 'Librarie',
        city: 'Yaoundé',
        rating: 4.7,
        images: ['https://images.unsplash.com/photo-1507842217121-9e96e4430330?w=500'],
        shop: { name: 'Peuples Noirs', address: 'Tsinga, Yaoundé' },
        location: { lat: 3.8860, lng: 11.5060 },
        tags: ['Livres', 'Culture', 'Lecture'],
        detailsUrl: '/search/25'
    },
    {
        id: '26',
        name: 'Pharmacie de la Cathédrale',
        description: 'Ouverte 24h/24. Conseils, parapharmacie et médicaments.',
        price: 0,
        type: 'shop',
        category: 'Santé',
        city: 'Yaoundé',
        rating: 4.6,
        images: ['https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500'],
        shop: { name: 'Pharma Cathédrale', address: 'Poste Centrale, Yaoundé' },
        location: { lat: 3.8600, lng: 11.5170 },
        tags: ['Santé', 'Garde', 'Médicaments'],
        detailsUrl: '/search/26'
    },
    {
        id: '27',
        name: 'Maison H',
        description: 'Décoration intérieure, mobilier moderne et design.',
        price: 0,
        type: 'shop',
        category: 'Maison',
        city: 'Yaoundé',
        rating: 4.8,
        images: ['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=500'],
        shop: { name: 'Maison H', address: 'Bastos, Yaoundé' },
        location: { lat: 3.8770, lng: 11.5130 },
        tags: ['Déco', 'Meubles', 'Design'],
        detailsUrl: '/search/27'
    },
    {
        id: '28',
        name: 'Kajazoma Concept',
        description: 'Restaurant gastronomique et galerie d\'art. Ambiance unique.',
        price: 15000,
        type: 'product',
        category: 'Restauration',
        city: 'Yaoundé',
        rating: 4.9,
        images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=500'],
        shop: { name: 'Kajazoma', address: 'Mfandena, Yaoundé' },
        location: { lat: 3.8950, lng: 11.5450 },
        tags: ['Art', 'Gastronomie', 'Luxe'],
        detailsUrl: '/search/28'
    },
    {
        id: '29',
        name: 'Sanza Night Club',
        description: 'La référence des nuits yaoundéennes. Musique, boissons et ambiance.',
        price: 5000,
        type: 'service',
        category: 'Loisirs',
        city: 'Yaoundé',
        rating: 4.1,
        images: ['https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=500'],
        shop: { name: 'Le Sanza', address: 'Hippodrome, Yaoundé' },
        location: { lat: 3.8690, lng: 11.5110 },
        tags: ['Fête', 'Club', 'Danse'],
        detailsUrl: '/search/29'
    },
    {
        id: '30',
        name: 'Marché du Mfoundi',
        description: 'Le grand marché de Yaoundé. Fruits, légumes, vivres frais.',
        price: 0,
        type: 'shop',
        category: 'Marché',
        city: 'Yaoundé',
        rating: 4.2,
        images: ['https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=500'],
        shop: { name: 'Marché Mfoundi', address: 'Centre Ville, Yaoundé' },
        location: { lat: 3.8615, lng: 11.5185 },
        tags: ['Marché', 'Frais', 'Local'],
        detailsUrl: '/search/30'
    }
];
