server:
  port: 8085

spring:
  application:
    name: geo-service
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_REDIS_SSL_ENABLED:false}

app:
  nominatim:
    url: https://nominatim.openstreetmap.org
    user-agent: "Yowyob-Service-1.0 (contact@yowyob.com)"
